name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'vite.config.ts'
      - 'tsconfig.json'
      - 'tsconfig.node.json'
      - 'package.json'
      - '!.github/**'
      - '!.husky/**'
      - '!.vscode/**'
      - '!**/README.md'
      - '!**/CHANGELOG.md'
      - '!**/LICENSE'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Setup PNPM
        id: pnpm-install
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build Packages
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_UPLOADS_URL: ${{ secrets.VITE_UPLOADS_URL }}
          VITE_USER_KEY: ${{ secrets.VITE_USER_KEY }}
        run: pnpm run build

      - name: ls
        run: ls

      - name: Copy to Nest
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: dist
          dst_path: /public
          dst_owner: alextim
          dst_repo_name: nest-test-app

